### ISSUE TITLE
Anim frames gets instantly cut if user starts typing into framebox

### ISSUE THREAD

**Issue by 77ZaRR77** [zturtleman/mm3d#121]
What I mean is I were animating skeleton model, then decided to cut anims from 20 frames to 17. 
Started typing 17 number, and as soon as I typed 1 all frames cleared. 
Maybe pressing Enter for confirming or smth needed?
And again, don't want to be annoying. Interested how others uses this.

**Comment by mick-p1982** [comment]
Yeah, most of MM3D is untested territory from what I can tell doing a rewrite on it at present. I guess a work around for you is to copy/paste your value into it. You probably know that and just want to file a bug?

I am developing a new strain of MM3D (https://github.com/mick-p1982/mm3d) that will hopefully it will get integrated into this code but I'm not using Qt or any of the UI parts, which is where this bug is located. I'm currently doing an overhaul of the animation facilities.

**Comment by zturtleman** [comment]
Fixed in 838a1e56bdfe937a8515c53636b43104186e808a.
