### ISSUE TITLE
objfilter.cc maybe missing break statement. Not documented intentional (Not sure myself)

### ISSUE THREAD

**Issue by mick-p1982** [zturtleman/mm3d#152]
https://github.com/zturtleman/mm3d/blob/8f121241275d3f52dcd0eaab6ef846c8c0b23ded/src/libmm3d/objfilter.cc#L284

**Comment by zturtleman** [comment]
It looks like there should be a `break`, otherwise these cases run the wrong state.

https://github.com/zturtleman/mm3d/blob/8f121241275d3f52dcd0eaab6ef846c8c0b23ded/src/libmm3d/objfilter.cc#L274-L281

It looks like `. 1` will copy `1` as a decimal digit in `case OFWS_AfterDecimal` rather than starting a new number in `case OFWS_Whitespace`. (Arm chair theory of course.)

**Comment by mick-p1982** [comment]
I haven't worked with OBJ in 20 years, if you have any idea, is it possible most export jobs don't enter this case? I have exported a few OBJ files with MM3D.

**Comment by zturtleman** [comment]
`writeStripped( "1. 1.000000" )` without break: `1. 1.000000`; with break: `1. 1.0` (correctly stripped zeros).

Yeah, after farther inspection it looks like it could only go wrong in MTL `map_Kd` texture filename (which shouldn't be removing trailing zeros in the first place). Fixed in https://github.com/zturtleman/mm3d/compare/8f121241275d3f52dcd0eaab6ef846c8c0b23ded...7c81c59dcb5d2b640aff749fbb64a4170fc81a8d. Thanks.

**Comment by mick-p1982** [comment]
Thanks for giving this proper attention.

FWIW looking at `strdup` around that change (been removing these) (a) there's a std::string version replaceSlash (I think) and (b) getRelativePath uses it, opportunistically, on both arguments (so replaceSlash is redundant here.)
