### ISSUE TITLE
Rotating bone joints in animation mode using properies panel doesn't always take affect

### ISSUE THREAD

**Issue by zturtleman** [zturtleman/mm3d#16]
However using the move tool afterward causes it to take affect. Might be updating joint rotation but not updating the joint matrix calculated from rotation and translation values or something.

Rotate tool works correctly.

**Comment by zturtleman** [comment]
Fixed in https://github.com/zturtleman/mm3d/commit/a093e5a3b1d35bb1e2a0a7766f60be8c55b60421.

**Comment by mick-p1982** [comment]
What about the two menu options: Set Rotation Keyframe and the next? They look like no-op operations.

I don't know how animating the models work... but if you have to choose these two options to modify a frame that's ridiculous? Should they be removed.

P.S. Something else that bothers me is Mode::translateSelected that the translation tools use. Instead of taking a vector it takes a matrix. I can't imagine what the matrix does, but there is a corresponding Vector method that takes a matrix too. Consumers only use vectors. I think maybe the matrix multiplies itself with its own translation component first. As weird as that is I can't imagine it doing anything else. 

There's no shortage of head-scratchers in this code. I can't possibly report everything. It would be more harm than good I think. (Unrelated the "model_status" function in `modelstatus.h` is not even using `model_status_get_object` so that the whole setup is pointless. It's defined in `statusbar.cc` instead of `modelstatus.cc`. Maybe these things were added in haste one day to try to make the code suitable for some other use case. I don't know.)

**Comment by mick-p1982** [comment]
Follow-up comment: I think both amount to a no-op MU_SetAnimKeyframe/MU_MoveFrameVertex undo record. In which case, there's at a minimum no need for both. And it's harebrained to say the least. Seems like something vestigial to me.
