### ISSUE TITLE
1.3.13 Minor Animation Issue When Starting New Animation

### ISSUE THREAD

**Issue by Enjay001** [zturtleman/mm3d#174]
Like the title says, it's a minor issue - and I mean _very_ minor - but it had me scratching my head for a few seconds.

With a model that does not have any animation loaded, carry out the following steps:

Got to Animation/Animation Sets...

Select "Frame Animation" and create a new animation.

Go to Animation/Start Animation Mode...

Your new animation should be selected, but it doesn't currently have any frames, so the windows are blank.

Use the little arrows beside  the "Frames" box to increase the number of frames.

At this point in the previous version, the windows would have a picture of the model as soon as the frame count was non-zero.  With 1.3.13 the windows stay blank until you click somewhere else, then the model appears.

Told you it was a minor issue. ;)

**Comment by zturtleman** [comment]
This was a side affect of deferring updating the frame count until done typing e.g., pressing enter or clicking off the Frames field to avoid truncating frames to 1 when typing 10.

It may be possible to handle Frames up/down buttons separately from typing, I'm not sure. (Surprisingly 'don't trigger value changed event until user is done editing value' doesn't seem to be a feature supported by Qt.)

Instead of custom rolled "delayed typed value update" it might make sense to add a button to update frame count or replace Frames field with a pop-up dialog to change amount.

I'll look into it for the next release.

**Comment by Enjay001** [comment]
Cool.  Now that I know how to get it to update, it's only a minor inconvenience but the suggestions you made certainly make sense.  Thanks.

**Comment by zturtleman** [comment]
The dialog for creating a new animation now contains the frame count and defaults it to 10 so this shouldn't be commonly encountered. (Created from Animation Mode animation list: https://github.com/zturtleman/mm3d/commit/048fa89860e36472807498db57af33b4ca82a777, Created from Animation Sets: https://github.com/zturtleman/mm3d/commit/de126d90a885c7e7ff914c2a0bc9d00aa4920771.)

**Comment by zturtleman** [comment]
This is now properly fixed. Clicking frame count +/- in animation mode will immediately update the frame count. I had to disable text editing of the frame count but it can be done in the New or  Edit Animation windows. https://github.com/zturtleman/mm3d/commit/eb1c1464beb81be740866922d9e20d48f844576e
