### ISSUE TITLE
two years passed without release

### ISSUE THREAD

**Issue by alexmyczko** [zturtleman/mm3d#188]
Hi and thank you for your work on mm3d,

I got this report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034674
and was curious if you could tag a new release?

Best,

if you could rename README to README.md it would also look much better, would that be possible?

**Comment by zturtleman** [comment]
renamed readme

**Comment by zturtleman** [comment]
Hello. The bug report filed against Maverick _1.3.12_ referenced this commit (https://github.com/zturtleman/mm3d/commit/f00fdd5f2a27292a646a23ba34f80be50ab9844c) which is included in the Maverick 1.3.13 release from 2021. The only changes since then are from the past two weeks but I am considering a new release.

It looks like the commit could be backported to 1.3.12 but I don't currently maintain past releases. Does Debian stable accept general bugfix-only updates to applications?

I found how to stop automake from requiring a "README" file, so I've now [renamed the readme file](https://github.com/zturtleman/mm3d/commit/dcab85ebda12f380c045584900fc571712fe6ea6).

Regarding the Debian package, could you remove listing blender, wings3d, and yafray as recommends (shown as "rec:" lines on https://packages.debian.org/bullseye/mm3d)? They are fine software but apt and GNOME Software install recommended packages by default. So `apt install mm3d` also installs blender and wings3d. It can be avoided using `apt install --no-install-recommends mm3d` but it's an odd workaround.

**Comment by zturtleman** [comment]
I tagged a new [v1.3.14](https://github.com/zturtleman/mm3d/releases/tag/v1.3.14) release. I don't think I can help with the 1.3.12 issue in Debian stable, so closing issue. Thanks.

**Comment by umlaeute** [comment]
just here to chime in: Debian/bookworm ships with v1.13.13 and the bug has indeed fixed been there.

As Debian/bookworm is currently in "deep freeze" (that is: the scheduled release date for Debian is 2023-06-10), we will ship a fixed version within Debian pretty soon, so afaict no action is required from your side (regarding our bug [#1034674](https://bugs.debian.org/1034674)).

Another implication of the "deep freeze" is that we won't be able to demote the "recommends" to a mere "suggests" (which won't get installed automatically) until Debian/trixie
