### ISSUE TITLE
Large poly counts

### ISSUE THREAD

**Issue by philosophofee** [zturtleman/mm3d#29]
Hi, found this software after looking for some sort of update to MM3D. I was wondering if there's any way you could optimize the software for large models? I love the interface for MM3D but whenever I work with a high poly count model it always tends to have issues. 

For one, whenever I load an .ms3d file exported by Milkshape that has a certain amount of polygons - that is rigged - the rigging tends to break entirely whenever I rotate a bone. 

The following model is Norman Jayden from the PS3 game Heavy Rain. 

![image](https://user-images.githubusercontent.com/32121493/48148945-f219b200-e288-11e8-9166-5e842ab280ec.png)
![image](https://user-images.githubusercontent.com/32121493/48148980-065daf00-e289-11e8-85d6-3cfc0776911e.png)

On the flip side, exporting an .ms3d file with a high poly count results in a failure to load within Milkshape. So on both ends, high poly models have issues between MM3D and MS3D.

Another issue is that whenever you delete a significant amount of polygons, the program freezes for a very long time. This is understandable yet seemingly fixable with optimizations, I would presume.

**Comment by zturtleman** [comment]
Fixed loading vertex weights from MS3D models created with Milkshape 3D 1.8.5 BETA 1 and weights for bone joint index over 128. https://github.com/zturtleman/mm3d/commit/caaf23869f56f3f9609cbdc21849424ddcbea2cb, https://github.com/zturtleman/mm3d/commit/86ffb3e80e2228edfe2e2105e2d5a18fbc75c01a

Exporting large poly models to MS3D now errors instead of creating a invalid model. https://github.com/zturtleman/mm3d/commit/773654fce1d6cb9cd5dea3ba65853699e2299efd

Slow deleting polygons is now a separate issue (#30).
