### ISSUE TITLE
Allow changing the viewport background color

### ISSUE THREAD

**Issue by zturtleman** [zturtleman/mm3d#43]
It's a nice blue but it would be nice if could use grey like other most other model editors (or any color).

**Comment by KuehnhammerTobias** [comment]
Something that fits dark themes would be awesome. If you use dark themes for any other sofware you really get used to it very soon, it keeps your eyes healthy.

**Comment by mick-p1982** [comment]
I don't see this as practical. If you choose a gray color, the selection rectangle will disappear. And other colors will have bad contrast, as the current color does, with greens.

To work, a system would have to take note of every color that is used, and provide a control panel to change the colors. Alternatively, a different color scheme could work, but that would be easier to implement by selecting from predefined color configuration files.

Personally I think I like the color scheme. It's funny because teal can be one of the worst colors for backgrounds, but it seems to work well here. I think it might not be good for displaying models. I've done a lot of tests with background colors and large model sets, and considered black or dark blue to look best and complement AA effects best. But modeling and showcasing are different matters.

**Comment by mick-p1982** [comment]
For the record, the xor on gray problem I mentioned before can be solved without anything complicated by using 128,128,128 for the color instead of white. White is no different from the GL_INVERT operation.

It turns the teal color to dark green. It's always visible, but it's a little weird because it sometimes darkens/lightens but other times it looks like an invert too, depending on the color. Still, it seems safest. I think it may be what is most commonly used with colored xor.

**Comment by Symbian9** [comment]
Yes, adding "Canvas Color" & "Grid Lines Color" into "Viewport Settings" is really missed & but highly wanted feature:

![Screenshot_2022-01-01_10-20-38_cut](https://user-images.githubusercontent.com/13188580/147850123-770edd66-8aa9-448f-bcbe-ade776a8f87a.png)

**Comment by zturtleman** [comment]
![Screenshot from 2024-07-31 03-45-50--cropped](https://github.com/user-attachments/assets/521cb8dc-7ec3-4b9f-84d0-d578955eae0c)
There is now two color schemes for the model background; the original and a new darker teal (half brightness). The model background can be set in View -> Viewport Settings to Automatic, Light, or Dark. 17d96678e7fb0fb0a1997c1a152bcc03e2607fef

The help browser has also been fixed for dark mode. It was previously unreadable white text on a light gray background. 8efd844c41bc965b0f286d2e9fccf0116c8042da

**Comment by m-7761** [comment]
Random idea: I recently added a Color tool for coloring elements, including skin weights. It lets the background be targeted for coloring, or clicking on "nothing". I've also let it color Joints and Points and triangle vertices (i.e. 3 colors per triangle) so there is potential for vertex color data. I have to save it still though. https://github.com/m-7761/mm3d/releases
