### ISSUE TITLE
./configure has syntax error--unexpected QT_VERSION_MINOR

### ISSUE THREAD

**Issue by poikilos** [zturtleman/mm3d#44]
```
checking for Qt... expr: syntax error: unexpected argument 'QT_VERSION_MINOR,'
no
checking Qt OpenGL... failure
configure: error: Failed to link Qt with OpenGL support.
```
Can you help with that?

**Comment by zturtleman** [comment]
What operating system version and Qt 5 version are you using?

**Comment by zturtleman** [comment]
I think you can avoid the issue using:

```
./configure --with-Qt-include-dir=(Qt 5 include directory)
```

The code below is probably where the issue is but I'm not sure what is causing it. If you want you can try changing it and re-running `./autosetup.sh && ./configure` to see if you fixed it. Otherwise I can try to use a virtual machine with (your operating system) when I have time.

https://github.com/zturtleman/mm3d/blob/0f4170788af8f19f8331ae87d515173b71763c27/acinclude.m4#L868-L870

**Comment by poikilos** [comment]
Those lines didn't change in that version. I'm assuming you just mentioned a commit since you wanted the issue to "permalink" the correct lines, and GitHub added confusing links. Here's a link they should have added to your quote, for future reference: https://github.com/zturtleman/mm3d/blob/0f4170788af8f19f8331ae87d515173b71763c27/acinclude.m4#L868

Thanks for the tip about `--with-Qt-include-dir=`. Here are some tests:
* `./configure --with-Qt-include-dir=/usr/include/qt5` fails with:
```
checking for Qt... yes:
    QT_CXXFLAGS=-I/usr/include/qt5
    QT_DIR=
    QT_LIBS=-lQt5Core -lQt5Gui -lQt5Widgets -lQt5OpenGL  
    QT_UIC=
    QT_MOC=
    QT_RCC=/usr/bin/rcc
    QT_LRELEASE=
    QT_MACDEPLOYQT=
checking correct functioning of Qt installation... failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```
* ./configure --with-Qt-include-dir=/usr/include/qt5 fails with same output except Qt instead of qt5, and with the addition of `-L/usr/lib64` after QT_LIBS.
  - I'm confused at why /usr/include/qt5 contains subdirectories with h files (they are not symlinks) but /usr/include/Qt* lists all separate subdirectories h files as well (but fewer): <https://pastebin.com/V1Mh2zSk>

**Comment by zturtleman** [comment]
Yeah, the commit hash is because of using a permanent link. If `QT_VERSION_MINOR` is not removed as expected on line 868 then I think the actual error could be happening with the printf on line 870.

It's odd that Qt rcc program is found but the uic, moc, and lrelease programs are not. :confused: 

I think /usr/include/Qt* (i.e., Qt3Support) are for Qt 4. Excluding /usr/include/Qt5GStreamer which is separate project from Qt.

configure works with Debian/Ubuntu ([with these packages](https://github.com/zturtleman/mm3d/blob/master/.travis.yml)). What OS are you using?

**Comment by poikilos** [comment]
Fedora 29

**Comment by zturtleman** [comment]
configure should be fixed on Fedora 29 now (https://github.com/zturtleman/mm3d/commit/f4ae840a9e4282a8433a137b568ee1506851188a). Build dependencies for Fedora and Debian have been added to the README.

**Comment by poikilos** [comment]
Thanks! It is working now. I was able to complete the rest of the steps as well, and the program runs.

**Comment by InFerYes** [comment]
I have this same error on Arch Linux.

When I use `./configure --with-Qt-include-dir=/usr/lib64` I get 
```
checking for Qt... yes:
    QT_CXXFLAGS=-I/usr/lib64
    QT_DIR=/usr
    QT_LIBS=-L/usr/lib64 -lQt5Core -lQt5Gui -lQt5Widgets -lQt5OpenGL
    QT_UIC=/usr/bin/uic
    QT_MOC=/usr/bin/moc
    QT_RCC=/usr/bin/rcc
    QT_LRELEASE=/usr/bin/lrelease
    QT_MACDEPLOYQT=
checking correct functioning of Qt installation... cat: bnv_qt_test.cpp: No such file or directory
failure
configure: error: Failed to find matching components of a complete
                  Qt installation. Try using more options,
                  see ./configure --help.
```

How to proceed?

**Comment by zturtleman** [comment]
It doesn't seem like the same problem. I opened a new issue with your comment at https://github.com/zturtleman/mm3d/issues/161.
