### ISSUE TITLE
debian and ubuntu packages

### ISSUE THREAD

**Issue by alexmyczko** [zturtleman/mm3d#9]
this is not really an issue but what about adding yourself to AUTHORS? Meanwhile the debian and ubuntu packages have a checked out version 1.3.9 what about making a release too?

**Comment by zturtleman** [comment]
Okay, I added myself to AUTHORS. I'll try to finish up the the macOS and Windows issues (#2, #7) soon and tag a 1.3.9 release.

**Comment by alexmyczko** [comment]
do you have an idea how i could get rid of this profiling bug? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=517564
i was able to reproduce it with 1.3.9 checkout:
profiling:/build:Cannot create directory
profiling:/build/buildd/mm3d-1.3.7/src/libmm3d/filedatasource.gcda:Skip
profiling:/build:Cannot create directory
profiling:/build/buildd/mm3d-1.3.7/src/libmm3d/filedatadest.gcda:Skip
profiling:/build:Cannot create directory
profiling:/build/buildd/mm3d-1.3.7/src/libmm3d/bsptree.gcda:Skip
profiling:/build:Cannot create directory
profiling:/build/buildd/mm3d-1.3.7/src/libmm3d/txtfilter.gcda:Skip
profiling:/build:Cannot create directory
profiling:/build/buildd/mm3d-1.3.7/src/libmm3d/tgatex.gcda:Skip
profiling:/build:Cannot create directory
profiling:/build/buildd/mm3d-1.3.7/src/libmm3d/rawtex.gcda:Skip
profiling:/build:Cannot create directory
...

**Comment by zturtleman** [comment]
I haven't seen those profile messages but I haven't compiled 1.3.7.

The [Ubuntu packages](https://launchpad.net/ubuntu/+source/mm3d) fail to configure because the linker can't find the Qt libs (see [buildlog](https://launchpad.net/ubuntu/+source/mm3d/1.3.9-2/+build/14314032)). It's configured with `--with-Qt-lib-dir=/usr/lib/x86_64-linux-gnu/qt5` but should be `/usr/lib/x86_64-linux-gnu`. That is where the Qt libs are on Debian too. `/usr/lib/x86_64-linux-gnu` seems to be automatically searched by the compiler on Debian but not on Ubuntu. [Debian qtbase5-dev file list](https://packages.debian.org/sid/amd64/qtbase5-dev/filelist) &bull; [Ubuntu qtbase5-dev file list](https://packages.ubuntu.com/bionic/amd64/qtbase5-dev/filelist).
